version: 2

linters-settings:
  lll:
    line-length: 140
  funlen:
    lines: 70

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - dupl
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - govet
    - gosec
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - prealloc

service:
  golangci-lint-version: 2.1.6
  prepare:
    - echo "here I can run custom commands, but no preparation needed for this repo"

